var express = require("express");
var bodyParser = require("body-parser");
const path = require("path");
const routes = require("./routes");
const cors = require("cors");
const cookieParser = require("cookie-parser");
var app = express();
require("dotenv").config();
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
app.use(cookieParser());
app.use(cors());
app.use(express.static(path.join(__dirname, "files")));
app.use("/files",express.static("files"));
app.use("/", routes);
module.exports = app;
